# Simulation parameters
# Signature parameters
list_of_bases: ['A', 'C', 'T', 'G']
list_of_pairs: ['CA', 'CG', 'CT', 'TA', 'TC', 'TG']
num_signatures: 78
use_signatures: false
signature_alpha: 10

# Simulation setup
# num_samples_list: [10,20,30]
num_samples: 10
num_tumors: 1
read_len: 150
frag_len: 400 # Extract from bam
alpha_list: [10]
r: 3.783884 # Ideally fitted on your data
p: 0.0143027069773697 # Ideally fitted on your data
paired: True
WES: True
bulk: False
use_leaf_only: false
# error_rate_list: [0.0, 0.0, 0.0, 0.00001, 0.00001, 0.0001, 0.001]
error_rate_list: [0.001]
# clone_list: [2,4,6,8,10] 
clone_list: [2,4,6,8,10] 

# Mutation rate categories (M_i in the paper)
genome_length: 3095693983.0
# mutational_events: ["SNV", "CNV", "DEL", "DELSMALL", "INVERSION", "TRANSLOCATION", "BFB", "CHROMOTHRIP", "CHROMOPLEX", "INSERTIONSMALL", "KATAEGIS", "ANEUPLOIDY"]
mutational_events: ["SNV", "CNV", "DEL", "DELSMALL", "INVERSION", "TRANSLOCATION", "BFB", "CHROMOTHRIP", "INSERTIONSMALL", "KATAEGIS", "ANEUPLOIDY"]
ultralow_rates_list: [1.0e-15]
low_rates_list: [1.0e-15, 1.0e-13, 1.0e-10]
medium_rates_list: [5.0e-9, 4.0e-10, 9.0e-10, 3.0e-9]
high_rates_list: [3.0e-8, 9.0e-9, 7.0e-9]
ultrahigh_rates_list: [5.0e-8, 5.0e-7, 6.0e-7, 5.0e-8, 1.0e-7]

# Sequencing coverage and population
coverage_list: {"on_target": 50000, "off_target": 50}
# coverage_list: {"on_target": 500, "off_target": 0.5}
pop_size: 8.0e+8 # Effective population size (needed in coalescent theory)
num_single_cells: 100
liquid_biopsy: False

# Batch processing
batch_size: 1
subblock_size: 1

# Liquid biopsy fraction
ctdna_frac_list: [0.96]

# Reference genome simulation parameters
ref_coverage: 1
ref_clones: 10
ref_paired: true
ref_WES: false
ref_erate: 0.0
