snakemake_min_version: "7.30.1"
mambaforge_version: "24.7.1-0"

chr_regions: ["on_target", "off_target"]

signatures_url: "https://raw.githubusercontent.com/CMUSchwartzLab/MosaicSim/refs/heads/main/data/signatures.txt"

simulate_threads: 50